name: curly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  window_size: ^0.1.0
  bitsdojo_window: ^0.1.6
  google_fonts: ^6.3.0
  flutter_code_editor: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
